apiVersion: v1
kind: ConfigMap
metadata:
  name: codeflix-subscription-nginx-configmap
data:
  nginx.conf: |
    server {
        listen 80;
        index index.php index.html;
        root /var/www/public;

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass codeflix-subscription-api-service:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        location / {
            try_files $uri $uri/ /index.php?$query_string;
            gzip_static on;
        }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeflix-subscription-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeflix-subscription-nginx
  template:
    metadata:
      labels:
        app: codeflix-subscription-nginx
    spec:
      containers:
      - name: codeflix-subscription-nginx
        image: nginx:1.17-alpine
        command: ["/bin/sh", "-c", "mkdir /var/www/public; touch /var/www/public/index.php && nginx -g 'daemon off;'"]
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: nginx-configmap
            readOnly: true

      volumes:
        - name: nginx-configmap
          configMap:
            name: codeflix-subscription-nginx-configmap
            items:
              - key: nginx.conf
                path: nginx.conf

---

apiVersion: v1
kind: Service
metadata:
  name: codeflix-subscription-nginx-service
  labels:
    app: codeflix-subscription-nginx-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: codeflix-subscription-nginx
