name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Save build artifact
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: .

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: .
      - name: Execute lint via Pint
        run: vendor/bin/pint --test
      - name: Execute Unit tests
        run: php artisan test --testsuite=Unit

  # build:
  #   name: Build
  #   needs: tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Log in to DockerHub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USER }}
  #         password: ${{ secrets.DOCKER_HUB_PWD }}
  #     - name: Build & push da imagem do docker
  #       uses: docker/build-push-action@v3
  #       with:
  #         file: ./.docker/php/Dockerfile.prod
  #         push: true
  #         tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}, ${{ env.IMAGE_NAME }}:latest
